### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by xinshouke** [shupande/lcwy-crm#1]
ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./mock in D:\环卫\Code\lcwy-crm-master\src
 @ ./src/main.js 31:12-29

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/user.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../common/util in D:\环卫\Code\lcwy-crm-master\sr
nts
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/user.vue 7:12-37

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/user.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../api/api in D:\环卫\Code\lcwy-crm-master\src\co
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/user.vue 15:11-32

**Comment by shupande** [comment]
Sorry about that , This project not finish yet, If you insist , You should add mock.js  in node_modules.
